In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#np.arange(start,stop,step-size)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones(3)

array([ 1.,  1.,  1.])

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
#Returns specified number evenly spaced points over a specified interval (interval here is 0 - 5 and number of points is - 10)
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [16]:
#Identity matrix
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [19]:
#Create numpy arrays of UNIFORM DISTRIBUTION containing random numbers ranging from 0 to 1 - 1st way
print ("1D array")
print (np.random.rand(5))

print ("2D array")
print (np.random.rand(3,4))

1D array
[ 0.3372456   0.30566526  0.96817416  0.72764871  0.02911969]
2D array
[[ 0.97214248  0.69453913  0.50753346  0.27192119]
 [ 0.75724696  0.73985599  0.6608356   0.03050715]
 [ 0.94940769  0.12205541  0.30316024  0.01963856]]


In [20]:
#Create numpy arrays of NORMAL or GAUSSIAN DISTRIBUTION containing random numbers - 2nd way
print ("1D array")
print (np.random.randn(5))

print ("2D array")
print (np.random.randn(3,4))

1D array
[-0.00729128 -1.68673903  0.83077395  1.24396171 -0.02198541]
2D array
[[-0.12170399  0.52230682  0.36769425  1.5894091 ]
 [-1.23087818 -0.82765773  0.05452808  0.66416787]
 [ 0.70093257 -0.32076007  0.20378689 -0.49486466]]


In [21]:
#Create numpy arrays containing random numbers from specified inclusive low to exclusive high numbers - 3rd way
np.random.randint(1,100, 50)

array([22, 17, 95, 36, 79, 35, 68, 56,  3, 31, 83,  7, 74, 55, 29, 36, 70,
       76, 29, 61, 79, 54,  9, 41, 20, 80, 14, 74, 71, 38, 29, 15, 79, 96,
       35, 83, 27, 15, 48, 67, 34, 10, 95, 82, 22, 67, 93, 25, 71, 10])

In [37]:
arr1 = np.arange(25)

In [38]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr2 = np.random.randint(0,50,10)

In [25]:
arr2

array([28, 38, 38, 22, 15, 10, 13,  6, 32,  1])

In [41]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
#Error because we have only 25 elements in arr1 and we ask for 50 cols.. the matrix should be completely filled with the elements
#available. So, rows * cols should be = to no. of elements in the array
arr1.reshape(5,50)

ValueError: cannot reshape array of size 25 into shape (5,50)

In [28]:
arr2

array([28, 38, 38, 22, 15, 10, 13,  6, 32,  1])

In [29]:
arr2.min()

1

In [30]:
arr2.max()

38

In [31]:
# Index at which maximum element resides
arr2.argmax()

1

In [32]:
# Index at which minimum element resides
arr2.argmin()

9

In [42]:
# Returns the shape of the vector - notice no parenthesis
arr1.shape

(25,)

In [43]:
arr2.shape

(10,)

In [44]:
arr1.dtype

dtype('int32')

In [107]:
arr2.dtype

dtype('int32')

# NUMPY ARRAY INDEXING

In [106]:
arr3 = np.arange(0,11)

In [47]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr3[8]

8

In [49]:
arr3[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr3[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr3[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [54]:
arr3[5:]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr3[0:5] = 100

In [56]:
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
#Reset the array
arr3 = np.arange(0,11)

In [58]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slicearr3 = arr3[0:6]

In [63]:
slicearr3

array([0, 1, 2, 3, 4, 5])

In [65]:
slicearr3[:] = 99

In [66]:
slicearr3

array([99, 99, 99, 99, 99, 99])

In [67]:
#Numpy arrays and lists are different such that - lists when manipulated, doesnt affect the original lists.
#But numpy arrays when sliced and manipulated, also affects the original numpy array. This is because slicearr3 is a reference
#to arr3, its not a copy (as in case of lists)
arr3

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
#To make a copy of numpy array - do following
arr3_copy = arr3.copy()

In [69]:
arr3_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr3_copy[:] = 89

In [71]:
arr3_copy

array([89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89])

In [72]:
arr3

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr4 = arr1.copy()

In [75]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [80]:
arr4 = arr4.reshape(5,5)

In [81]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
arr4[0]

array([0, 1, 2, 3, 4])

In [85]:
arr4[0][3]

3

In [87]:
arr4[0,3]

3

In [88]:
arr4[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [90]:
arr4[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [91]:
arr4[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr4[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [93]:
arr4[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
arr5 = np.arange(1,11)

In [95]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr5_bool = arr5 > 5

In [102]:
arr5_bool

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [103]:
arr5 < 4

array([ True,  True,  True, False, False, False, False, False, False, False], dtype=bool)

In [100]:
arr5[arr5_bool]

array([ 6,  7,  8,  9, 10])

In [105]:
arr5[arr5<=3]

array([1, 2, 3])

# NUMPY OPERATIONS
### Array with Array

In [119]:
arr6 = np.arange(0,11)

In [120]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr6 + arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [122]:
arr6 - arr6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
arr6 * arr6

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [124]:
arr6 / arr6

C:\Users\danandi\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

### Array with scalars

In [125]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr6 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [127]:
arr6 - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [128]:
arr6 * 20

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [129]:
arr6 / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [133]:
arr6**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### Universal Array functions

In [132]:
np.sqrt(arr6)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [134]:
np.exp(arr6)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [135]:
np.max(arr6)

10

In [136]:
np.min(arr6)

0

In [137]:
np.sin(arr6)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [138]:
np.log(arr6)

C:\Users\danandi\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])